# The Political Correlates of Bad Banks

## Mark Hallerberg and Christopher Gandrud

### 16 July 2012

---

As part of its bailout terms with the European Union and International Monetary Fund, Spain is being required to create a public asset management company--a "bad bank". This asset management company (AMC) is intendend to acquire and dispose of the non-performing assets that have brought many Spanish banks close to collapse. Similar institiutions have recently been created in countries like Ireland and--in more decentralised forms--Germany. Many of the newest AMCs are being speedily constructed[^namaSpainSpeed] and as part of outside actors' requirements for financial assistance. This raises clear questions about how well these institutions are likely to 'stick' and be effective given individual country economic and political realities.

In this brief research note we aim to partially address this issue by looking at what types of *political systems* have created AMCs and how effective they have been.


[^namaSpainSpeed]: See: <http://namawinelake.wordpress.com/2012/07/11/spain-forced-to-establish-asset-management-company-as-part-of-bailout/>.
